language: java
jdk: oraclejdk8

notifications:
  irc:
    channels: chat.freenode.net#bitsquare.io
    template:
      - '%{message} (%{repository}#%{build_number}, %{duration})'
      - '%{repsitory}/%{branch} %{commit} %{author}: %{commit_message}'
      - '%{build_url}'
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
