language: java
jdk: oraclejdk8
sudo: false

install:
  - "apt-get purge openjdk*"
  - "add-apt-repository -y ppa:webupd8team/java"
  - "apt-get update"
  - "apt-get install oracle-java8-installer"

notifications:
  irc:
    channels: chat.freenode.net#bitsquare
    template:
      - '%{message} (%{repository}#%{build_number}, %{duration})'
      - '%{repository}/%{branch} %{commit} %{author}: %{commit_message}'
      - '%{build_url}'
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true