language: java
jdk:
    - oraclejdk8

script: mvn test

#notifications:
#  irc:
#    channels: chat.freenode.net#bisq
#    template:
#      - '%{message} (%{repository}#%{build_number}, %{duration})'
#      - '%{repository}/%{branch} %{commit} %{author}: %{commit_message}'
#      - '%{build_url}'
#    on_success: change
#    on_failure: always
#    use_notice: true
#    skip_join: true