language: java
jdk: oraclejdk8

before_install: 
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

notifications:
  irc:
    channels: chat.freenode.net#bitsquare
    template:
      - '%{message} (%{repository}#%{build_number}, %{duration})'
      - '%{repository}/%{branch} %{commit} %{author}: %{commit_message}'
      - '%{build_url}'
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true

env:
  - TERM=dumb

after_success:
  - ./gradlew jacocoTestReport coveralls
