language: java
jdk: oraclejdk8

install:
  - git clone -b bisq_0.14.4.1 https://github.com/bitsquare/bitcoinj.git
  - cd bitcoinj
  - mvn clean install -DskipTests
  - git clone https://github.com/bitsquare/libdohj.git
  - cd libdohj
  - mvn clean install -DskipTests
  - git clone https://github.com/bitsquare/btcd-cli4j.git
  - cd btcd-cli4j
  - mvn clean install -DskipTests
  - cd ..

script: mvn clean install -DskipTests

notifications:
  slack:
    rooms:
      - secure: H82Q57T5nRNDfVnxzlWZ2WoeGt71oq2eJGHbqJ4wP2tIc8b02UO9bztPKFxbm9slMu0JjxZdJfnHSgNZKfPVXrTqwPYRVjKqm7m9TynIlkQabV+yCI/oRvy4Xi/Xj7/aPvZat4s/bxjrtw9KwVdpmqWvRNNSgiTqQ4teBJ1uQGs=
    on_success: change
    on_failure: always
